name: gp_2024_25
description: A Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0  # Ensure this is the correct version
  cloud_firestore: ^5.4.4  # Ensure this is the correct version
  firebase_auth: ^5.3.1  # Ensure this is the correct version
