name: rawae
description: A Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0 # Ensure this is the correct version
  cloud_firestore: ^5.4.4 # Ensure this is the correct version
  firebase_auth: ^5.3.1 # Ensure this is the correct version
  google_fonts: ^6.2.1
  lints: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
