name:  gp_2024_25 
description: A Flutter project.

publish_to: 'none' # Remove this line if you plan to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0 # Add the latest version of firebase_core
  # Add other Firebase packages as needed
  cloud_firestore: ^5.4.4 # For Firestore, if needed
  firebase_auth: ^5.3.1 # For Authentication, if needed
