name: 2024-25_GP_14
description: A Flutter project.

publish_to: 'none' # Remove this line if you plan to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

