// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJQXIbUMDtdPYOes3YsvcE-nI5dDRnDoA',
    appId: '1:551192338228:web:710b5dfd110f596c840f61',
    messagingSenderId: '551192338228',
    projectId: 'rawae-1860f',
    authDomain: 'rawae-1860f.firebaseapp.com',
    storageBucket: 'rawae-1860f.appspot.com',
    measurementId: 'G-S1KC4KFSCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWXBzXN0rzO6CgzORxj289VlxRYc8o75Y',
    appId: '1:551192338228:android:29b94486d6159a73840f61',
    messagingSenderId: '551192338228',
    projectId: 'rawae-1860f',
    storageBucket: 'rawae-1860f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXSPQcnF4oHj5nf3PvG1evDNQGUUo7Kwo',
    appId: '1:551192338228:ios:6e3ab30df4bda9cc840f61',
    messagingSenderId: '551192338228',
    projectId: 'rawae-1860f',
    storageBucket: 'rawae-1860f.appspot.com',
    iosBundleId: 'com.example.app.rawae',
  );
}
